### ISSUE TITLE
프로필을 편집하고싶다.

### ISSUE THREAD

**Issue by woorim960** [g-world-hackaton/g-world-fe#10]
# UserStory
> 사용자로서 프로필을 편집하고싶다.
내가 원하는대로 커스터마이징하기 위해.

# Task
## Front
- [ ] 프로필 편집 화면 구현
- [ ] 프로필 사진 수정 기능

### Call API
- [ ] 프로필 정보 조회
- [ ] 프로필 정보 저장 (`url`, `nickname`, `content`)

## Back
- [ ] [프로필 정보 조회 API 설계](https://github.com/g-world-hackaton/g-world-apis/issues/1)
- [ ] 프로필 정보 조회 API 구현

- [ ] 프로필 정보 저장 API 설계
- [ ] 프로필 정보 저장 API 구현

# 참고 이미지

![Image](https://github.com/g-world-hackaton/g-world-fe/assets/56839474/21adbcf6-0023-4e87-b4c2-9b97a5022ba2)
![Image](https://github.com/g-world-hackaton/g-world-fe/assets/56839474/adaa6938-fadd-4987-8b75-d17eaba5b909)
