### ISSUE TITLE
지마켓홈에서 "파워컨슈머의 추천 아이템"을 보길 원한다.

### ISSUE THREAD

**Issue by woorim960** [g-world-hackaton/g-world-fe#25]
# UserStory
> 사용자로서 지마켓 홈에서 "파워컨슈머의 추천 아이템"을 보길 원한다.  
파워 컨슈머의 상품은 신뢰가 있기 때문.

# Task
- [ ] 기존 지마켓 UI와 어떻게 상호작용 할 것인지 고민
- [ ] 아이템 목록 컴포넌트 구현
- [ ] 파워컨슈머 추천 아이템 목록 조회 API 연동

## 기존 지마켓 UI와 어떻게 상호작용 할 것인지 고민
> 개발할 사람이 최종 결정 후 구현.
우림: "시연할 UI 사이즈에 맞춰 지마켓 앱 캡쳐한 후 구현 기능 외의 부분은 이미지만 로드하고, 새 기능만 이미지 사이에 컴포넌트를 조립한다."

# 참고 이미지

![Image](https://github.com/g-world-hackaton/g-world-fe/assets/56839474/7686688e-ad4b-4afe-b143-b4b86d9c56ca)
