### ISSUE TITLE
매거진 별 "상세 정보"를 보길 원한다.

### ISSUE THREAD

**Issue by woorim960** [g-world-hackaton/g-world-fe#28]
# UserStory
> 사용자로서 매거진 별 "상세 정보"를 보길 원한다.
상품의 자세한 리뷰를 통해 내가 원하던(구매하고싶은) 상품인지 파악하기 위해.

# Task
## Back
- [ ] 매거진 상세화면 조회 API 설계
- [ ] 매거진 상세화면 조회 API 개발

## Front
- [ ] 매거진 상세화면 레이아웃 개발
- [ ] Image 컴포넌트 개발
![상세화면 2](https://github.com/g-world-hackaton/g-world-fe/assets/56839474/0c8dd62c-617f-479a-845d-365ac4838c0b)
- [ ] "연결된 상품" 컴포넌트 개발
![상세화면](https://github.com/g-world-hackaton/g-world-fe/assets/56839474/4ac6671b-a6d9-4841-a0e5-65faf19fb5da)
- [ ] "상세 컨텐츠" 컴포넌트 개발
![Image](https://github.com/g-world-hackaton/g-world-fe/assets/56839474/e6102e90-e15e-4e3d-a0ff-e2cad2f23d65)
- [ ] 나머지 레이아웃 개발 (댓글 기능 구현은 보류한다.)
- [ ] 매거진 상세화면 조회 API 연동
